Aidoku/Aidoku

- Shared/Extensions/UIImageColors.swift
- iOS/Info.plist
- iOS/SceneDelegate.swift
- iOS/UI/Base/MangaListSelectionHeader.swift
- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Reader/Page/ReaderInfoPageView.swift
- iOS/UI/Reader/ReaderViewController.swift
- iOS/UI/Search/SearchViewController.swift
- iOS/UI/Settings/SettingsViewController.swift
This PR adds some fixes and features to Aidoku:
- Settings has been moved from library into its own tab for easy access
- A ContextMenu has been added to save the current page to a user's photo gallery (can present a share sheet in the future)
- Color schemes have been fixed for the in-between page for chapters
> Settings in tab view, contextmenus, and color fixes

- Aidoku.xcodeproj/project.pbxproj
- iOS/AppDelegate.swift
- iOS/UI/Reader/CircularProgressView.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
- iOS/UI/Reader/ReaderViewController.swift
- iOS/UI/Settings/SettingsViewController.swift
The changelog is as follows:
- Fix the black screen bug that was appearing in the reader (after fixing the reload bug)
- Add the option to downsample images in settings (can be moved inside the reader later on)
- Add a circular progress bar instead of apple's progress spinner
- Set memory limits for kingfisher so 25% of a user's resources isn't used up
> Various fixes for v0.2

- .github/workflows/nightly.yml
Add nightly builds to be posted on the Github. These are considered as development builds and anyone who does sideload them uses them at their own risk.
Highly recommend a backup!
But it's still a good idea to have nightlies for users who want features now.
> Add Github actions

- Shared/Wasm/Imports/WasmHtml.swift
`Element.ownText()` returns text owned by this element, without combining children's texts. For example:
```
<div class="col-md-4">
17 May. 2022
<a href="https://mega.nz/file/6ewVEJzL#iIk392r2k7bxCV8CAwa44OO8zuLrrY2sHgNQBf4uIn4" class="btn btn-primary btn-xs download">Download</a>
</div>
```
`div.ownText()` would return only `17 May. 2022` instead of `17 May. 2022 Download`.
----
`Element.data()` is for getting data inside a `<script>` tag.
> Add getting an element's own text and data to WasmHtml

- Aidoku.xcodeproj/project.pbxproj
- Aidoku.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iOS/AppDelegate.swift
- iOS/Old UI/Base/Manga/MangaCoverCell.swift
- iOS/Old UI/History/HistoryTableViewCell.swift
- iOS/Old UI/Manga/Tracking/TrackerSearchTableViewCell.swift
- iOS/UI/Browse/SourceTableViewCell.swift
- iOS/UI/Common/Manga/MangaGridCell.swift
- iOS/UI/Manga/MangaCoverViewController.swift
- iOS/UI/Manga/MangaDetailHeaderView.swift
- iOS/UI/Migration/MangaGridView.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
- iOS/UI/Reader/Readers/Webtoon/ReaderWebtoonImageNode.swift
- The `ImageTaskDelegate` was removed so I had to modify how the image tasks where loaded
- ~~I'm not really sure about the changes on `ReaderPageView`~~
- I added a custom `DataLoader` to the shared `ImagePipeline` as it's recommended in the [docs](https://kean-docs.github.io/nuke/documentation/nuke/cache-layers#Aggressive-Disk-Cache) if using a custom `DataCache`
> Migrate to Nuke 12

- iOS/UI/Reader/Page/CropBordersProcessor.swift
Two things done here:
- Pass nil to `CGContext` `data` so we don't need to worry about managing its memory
- Use `UIGraphicsImageRenderer` to crop the `CGImage`. For some reason the `cropping` call wasn't releasing the original image reference in the nuke processor but doing it inside the renderer frees the memory used.
> Crop borders: more memory fixes

- Shared/Localization/en.lproj/Localizable.strings
- Shared/Localization/pt-BR.lproj/Localizable.strings
- iOS/UI/Manga/MangaDetailHeaderView.swift
Allow to copy manga title when long pressing the title in the manga details.
I added translation to my language only. It's probably just a matter of using a translator for the others since it's a basic vocabulary word. I can do that if it's not a problem.
> Copy manga title from manga details

- iOS/AppDelegate.swift
- iOS/UI/Reader/Page/CropBordersProcessor.swift
- Changed Nuke `dataCachePolicy` to `automatic`. So processed images are saved in memory cache, instead of the unprocessed ones.
- Disabled the `isStoringPreviewsInMemoryCache` Nuke option. This reduces the memory usage and in my tests it doesn't seem to affect anything.
- Removed the `UIGraphicsImageRenderer` in `CropBorderProcessor`. In my experience this doesn't fix anything, it just makes Xcode report the memory used to "Other Processes".
> Improve memory usage when using processors

- Shared/Wasm/Imports/WasmNet.swift
- Fixes mangadex search query and possibly other sources
It works but I'm still not sure, let me know if something can be improved.
> Fix double url string encoding in ios17

- Shared/Data/Downloads/DownloadManager.swift
Currently when downloading all chapters or unread chapters the download order is set from last to first.
This PR should reverse the order and instead download from first to last.
Having the order from first to last will allow users to start reading as soon as the first chapter is loaded.
1. Reversed order of chapters for `downloadAll` function
2. Reversed order of chapters for `downloadUnread` function
1. Have at least a manga in the library
2. Long press the title from the library
3. From the menu select "Download" -> "All"
4. In the download Que observe that the download order is from first to last
5. Clear the queue
6. Mark a few chapters as read
7. Back from the library on long press select "Download" -> "Unread"
8. Make sure the order is from first unread to last
> Reverse download order for all or unread chapters

- Shared/Localization/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/Old UI/Reader/ReaderSettingsViewController.swift
- iOS/Old UI/Settings/SettingsViewController.swift
- iOS/UI/Reader/ReaderViewController.swift
- iOS/UI/Reader/Readers/Paged/ReaderPagedViewModel.swift
This PR introduces settings for page reader background color. 
Users can choose from three options: system theme (dark or light), light, or dark. The default value is dark, respecting the original default dark background but users can change it anytime. Additionally, English translation is included. 
The aim of this PR is to address the problem described in: [Issue 77](https://github.com/Aidoku/Aidoku/issues/77).
> feat: adds page background color option

- Shared/Data/Downloads/DownloadManager.swift
- Shared/Sources/Source.swift
- iOS/UI/Reader/Readers/Paged/ReaderPagedViewModel.swift
I've modified the page fetching behavior for image loading to skip reading the contents of downloaded images and creating a base64 string out of it.
I'm not familiar with most of the codebase, but from what I've browsed, it seems Aidoku uses base64 strings to encode images from sources via Wasm. This is used during the downloading process, but effectively unused when displaying downloaded pages.
The inspiration for this change came out of Aidoku's handling of large chapters. Because base64 is effectively compressed data, it doesn't serve well when many large images are stored in memory. In my experience, the memory usage causes iOS to kill the app past 2 GB (iPhone 12), as well as create a long delay prior to loading images.
Closes #359
> Improve image loading for downloaded images

- Shared/Localization/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/Old UI/Settings/SettingsViewController.swift
- iOS/UI/Reader/ReaderViewController.swift
This PR closes #304 (enhancement).
After a user reads a downloaded chapter, the chapter will be deleted. I added a toggle in the Settings under Library Updating which is set off by default.
This is my first time pushing to prod, let me know if there's anything I should change.
> Add option to delete downloaded chapter after reading

- Shared/Data/Downloads/DownloadQueue.swift
Right now, downloads are added to queue regardless if they're already downloaded or not, which takes up unneeded space in the download queue dialog.
This commit adds a check in the function for adding them, to skip if it's already downloaded.
> Only add a download to queue if it doesn't already exist

- Shared/Localization/en.lproj/Localizable.strings
- iOS/Old UI/Reader/ReaderInfoPageView.swift
This closes #212 
A new UI label is added and displays when a chapter difference bigger than 1 is detected after going to a new chapter. Let me know if the text or styling should be changed. Maybe a warning icon should be displayed?
> Add warning message when chapters are being skipped

- iOS/UI/Library/LibraryViewController.swift
This adds "Migrate" to the right-click menu within the Library
> Migrate can now be accessed within the library directly

- iOS/UI/Library/LibraryViewController.swift
This adds a "Mark All" sub-menu to the Library view's right click menu
> Mark all as read/unread can now be accessed within the library directly

- Shared/Localization/en.lproj/Localizable.strings
- Shared/Managers/CoreData/CoreDataManager+History.swift
- iOS/Old UI/History/HistoryViewController.swift
- iOS/Old UI/Settings/SettingsViewController.swift
This closes #210 
On the history tab, I added a new action for clearing all history outside of manga in the user's library.
Should this new action be added to Settings on "Clear Read History"? Also, let me know if the string or anything else should be changed.
> Add action for clearing history excluding mangas in library

- iOS/UI/Reader/ReaderViewController.swift
This PR fixes the issue where the title-only chapters are skipped when getting previous chapter.
- Closes #429
- Fixed a bug where the previous title-only chapters were skipped if the current chapter was also title-only
| Chapter List | Before | After |
| :-: | :-: | :-: |
| ![chapter-list](https://github.com/user-attachments/assets/784d06f0-afc1-430a-bd53-08eaa248e9b3) | ![before](https://github.com/user-attachments/assets/7979ef17-8fd6-46bb-be94-a4fe42c09aa3) | ![after](https://github.com/user-attachments/assets/fd5da6f1-4037-419e-93e6-246b4db6f371) |
> fix(reader): wrong previous chapter

- Shared/Localization/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/Old UI/Settings/SettingsViewController.swift
- iOS/UI/Reader/ReaderViewController.swift
This fixes #517
Each chapter skipped in `getNextChapter()` will be appended to `chaptersToMark`. Once a chapter is finished, it and any skipped chapters are marked as read.
> Mark skipped duplicate chapters as read

- iOS/UI/Manga/MangaViewController.swift
- Closes #550
- Fixed a bug where unread title-only chapters were marked as read when syncing with tracker
| :-: | :-: |
| ![before](https://github.com/user-attachments/assets/7a99a096-833e-4cf5-8d86-f1d3d74d03a3) | ![after](https://github.com/user-attachments/assets/1e6f05a1-c46f-4c00-9321-9ac6ee45d015) |
> fix(manga): title-only chapters marked as read

- iOS/UI/Manga/MangaViewController.swift
- iOS/UI/Manga/MangaViewModel.swift
Makes sure sorting in any direction/method lets you mark "previous" chapters rather than chapters below the selected one. Also avoids marking the current chapter as read/unread when using "Mark previous".
- For example, if you select chapter 10, regardless of sorting direction, chapters 0-9 will be marked.
Closes: https://github.com/Aidoku/Aidoku/issues/139
- Excludes the selected chapter when using "Mark previous"
- "Mark previous" now marks previous chapters  in terms of upload date, chapter number, and source-order.
- Sorting descending after the changes:
- Upload date: latest to earliest
- Chapter: latest to earliest
- Source order: latest to earliest (same as before)
- Changed `MangaViewModel.getOrderedChapterList` to avoid breaking the reader.
Related: …
> Consistent sorting and fixes "Mark previous as read/unread"

- Shared/Localization/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/Old UI/Settings/SettingsViewController.swift
- iOS/UI/Reader/ReaderViewController.swift
Closes #547 
- Separated "Mark Duplicated Chapters" from requiring "Skip Duplicated Chapters" to be on
- changed getPrevChapter() to mark duplicate chapters from before it
- changed getNextChapter() to handle the two different settings:
- If not skipping dupes but marking, return the next chapter in the list and mark dupes as read
- If skipping but not marking, return the first non-duplicate chapter and keep dupes unread
- If neither, return the next chapter in the list in first iteration
- If both, return the first non-duplicate chapter and mark dupes
> Modify marking duplicate chapters option

- .github/workflows/supporting/altstore/apps.json
> Updated AltStore apps.json for missing entitlement

- iOS/UI/Reader/Readers/Webtoon/ReaderWebtoonViewController.swift
- Fixed an issue where images in webtoon reader were not saved to album
| :-: | :-: |
| ![album-before](https://github.com/user-attachments/assets/e7b83f42-d758-4c93-8ecc-1ae09c03e119) | ![album-after](https://github.com/user-attachments/assets/c180099b-d923-4b14-bb7e-58887df71df5) |
| <video src="https://github.com/user-attachments/assets/6d3821db-c761-4648-9b38-6a8d3b8effe4"> | <video src="https://github.com/user-attachments/assets/ddaa76c4-707d-4af5-bf22-7f4d9feae0c2"> |
> fix: save webtoon reader images to album

- Shared/Localization/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Library/LibraryViewModel.swift
- #79
- Added support for undoing and redoing removing manga from category
https://github.com/user-attachments/assets/61fea331-9720-46db-b7a8-76689faf8087
> feat(library): undo remove from category

- iOS/UI/Library/LibraryViewController.swift
This fixes this issue: [https://github.com/Aidoku/Aidoku/issues/663](https://github.com/Aidoku/Aidoku/issues/663)
Before (delete and add to category buttons at bottom are obscured by tab bar):
After:
> Hide Tab Bar when Tool Bar is shown in Library

- iOS/UI/Reader/ReaderViewController.swift
This PR provides a band-aid fix for the bug where the navigation bar overlaps the status bar.
- Closes #682
| :-: | :-: |
| ![before](https://github.com/user-attachments/assets/5135361c-d893-43bd-bae8-2bbf8ee8a74f) | ![after](https://github.com/user-attachments/assets/72a7570c-a63b-444a-a931-77220f9867ab) |
> fix: hide bars when scene enters foreground

- iOS/New/Views/Manga/ExpandableTextView.swift
- iOS/New/Views/Manga/MangaDetailsHeaderView.swift
The author and tag reproduction is used for sources prior to version 0.7, and there is no cost to add it.
The text in the description should allow selection and copying, and existing controls don't seem to simply achieve this.
> fix: the description is incorrect & allows description, author and tag to be copied
