- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
Add the following features:
- Pull to refresh support in library
- Increase reload button padding
> Add features for v0.1.1

- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
This commit fixes the reload issue in Aidoku v0.1.1
> Fix reload bug

- Shared/Data/Database/DataManager.swift
- Shared/Extensions/UIImageColors.swift
- iOS/UI/Base/Manga/MangaCollectionViewController.swift
- iOS/UI/Browse/BrowseViewController.swift
- iOS/UI/Browse/SourceViewController.swift
- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Manga/MangaViewController.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
- iOS/UI/Reader/ReaderViewController.swift
- iOS/UI/Search/SearchViewController.swift
- iOS/UI/Settings/BackupsViewController.swift
Get rid of all DispatchQueue calls since DispatchQueue is a legacy system.
Tested the app with these changes for 2-3 days and no issues have popped up.
> Completely update to swift concurrency

- Shared/Aidoku.xcdatamodeld/Shared.xcdatamodel/contents
- Shared/Data/Backup/Models/BackupLibraryManga.swift
- Shared/Data/Backup/Models/BackupManga.swift
- Shared/Data/Database/DataManager.swift
- Shared/Data/Database/Objects/LibraryMangaObject.swift
- Shared/Data/Database/Objects/MangaObject.swift
- Shared/Models/Manga.swift
- Shared/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/UI/Base/Manga/MangaCollectionViewController.swift
- iOS/UI/Base/Manga/MangaCoverCell.swift
- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Manga/MangaViewController.swift
- iOS/UI/Reader/PageManager/ReaderPagedPageManager.swift
- iOS/UI/Reader/PageManager/ReaderScrollPageManager.swift
- iOS/UI/Reader/ReaderViewController.swift
- iOS/UI/Settings/SettingsViewController.swift
Add various sort options to Aidoku's library
Resolves #15
> Add sorting functionality to library

- Aidoku.xcodeproj/project.pbxproj
- Shared/Data/Database/DataManager.swift
- Shared/Data/Downloads/DownloadCache.swift
- Shared/Data/Downloads/DownloadManager.swift
- Shared/Data/Downloads/DownloadQueue.swift
- Shared/Data/Downloads/DownloadTask.swift
- Shared/Data/Downloads/Models/Download.swift
- Shared/Extensions/FileManager.swift
- Shared/Models/Manga.swift
- Shared/Sources/Source.swift
- Shared/Wasm/Imports/WasmNet.swift
- Shared/en.lproj/Localizable.strings
- iOS/UI/Base/CircularProgressView.swift
- iOS/UI/Base/Manga/MangaCoverCell.swift
- iOS/UI/Library/DownloadQueueViewController.swift
- iOS/UI/Library/DownloadTableViewCell.swift
- iOS/UI/Library/LibraryViewController.swift
- iOS/UI/Manga/MangaChapterTableViewCell.swift
- iOS/UI/Manga/MangaViewController.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
- iOS/UI/Reader/PageManager/ReaderPagedPageManager.swift
- iOS/UI/Reader/PageManager/ReaderScrollPageManager.swift
> Add Downloads support

- Shared/zh_CN.lproj/Localizable.strings
> Chinese translation

- .swiftlint.yml
- Aidoku.xcodeproj/project.pbxproj
- Shared/Managers/CoreData/CoreDataManager+Chapter.swift
- Shared/Managers/CoreData/CoreDataManager+History.swift
- Shared/Managers/Manga/MangaManager.swift
- Shared/Sources/Source.swift
- Shared/Sources/SourceManager.swift
- iOS/AppDelegate.swift
- iOS/Scenes/Browse/BrowseViewController.swift
- iOS/Scenes/Browse/BrowseViewModel.swift
- iOS/Scenes/Common/SwiftUINavigationView.swift
- iOS/Scenes/Manga/MangaDetailHeaderView.swift
- iOS/Scenes/Manga/MangaViewController.swift
- iOS/Scenes/Migration/MangaGridView.swift
- iOS/Scenes/Migration/MangaToMangaView.swift
- iOS/Scenes/Migration/MigrateMangaView.swift
- iOS/Scenes/Migration/MigrateSearchMatchView.swift
- iOS/Scenes/Migration/MigrateSourceSelectionView.swift
- iOS/Scenes/Migration/MigrateSourcesView.swift
- iOS/Scenes/Migration/Models/MigrationState.swift
- iOS/Scenes/Migration/Models/MigrationStrategy.swift
- iOS/Scenes/Reader/ReaderViewController.swift
- iOS/UI/Browse/LanguageSelectViewController.swift
Adds a migration option to manga in library and on the browse page.
> Add basic migration

- Shared/Data/Downloads/DownloadManager.swift
- iOS/Scenes/Library/LibraryViewController.swift
> Update the library view to include downloading

- Shared/Extensions/String.swift
- iOS/Scenes/Library/LibraryViewModel.swift
- iOS/UI/History/HistoryViewController.swift
someone on the Discord told me to PR this...
adds: 
- author searching in library
- simple fuzzy searching
works fine based on my limited testing. my swift is horrible, so reviews would be nice if improvements can be made.
> Fuzzy search in library

- iOS/Scenes/Library/LibraryViewController.swift
- iOS/Scenes/Manga/MangaViewController.swift
- iOS/Scenes/Reader/Readers/Paged/ReaderPagedViewController.swift
- iOS/Scenes/Reader/Readers/Webtoon/ReaderWebtoonViewController.swift
- iOS/Scenes/Source/SourceViewController.swift
Fix issue #197 
https://user-images.githubusercontent.com/37344470/233849612-c5358902-ea10-4113-afd5-0a5790a92fca.mp4
> fix: app crashes when pressing share (iPad)

- Shared/Data/Backup/BackupManager.swift
- Shared/Extensions/FileManager.swift
closes https://github.com/Aidoku/Aidoku/issues/320
> feat: update backup sorting

- Shared/Localization/en.lproj/Localizable.strings
- Shared/Sources/SourceManager.swift
- iOS/UI/Browse/BrowseViewController.swift
- iOS/UI/Browse/BrowseViewModel.swift
Ability to pin and re-order sources in a new section above the installed sources section (while remaining below the update source section).
Closes #201   (Closes 201 not 244)
https://i.imgur.com/R0k8wjo.mp4
> Pinned source feature

- iOS/UI/Reader/Page/CropBordersProcessor.swift
This removes the ability to cook fried eggs on your iphone, I hope you don't mind
> Crop borders: downsample image

- iOS/UI/Reader/Page/CropBordersProcessor.swift
- iOS/UI/Reader/Page/ReaderPageView.swift
- iOS/UI/Reader/Readers/Webtoon/ReaderWebtoonImageNode.swift
> Apply crop borders before downsampling

- Aidoku.xcodeproj/project.pbxproj
- Shared/Aidoku.xcdatamodeld/.xccurrentversion
- Shared/Aidoku.xcdatamodeld/0.6.7.xcdatamodel/contents
- Shared/Aidoku.xcdatamodeld/0.6.xcdatamodel/contents
- Shared/Data/Backup/Models/BackupManga.swift
- Shared/Data/Database/Objects/MangaObject.swift
- Shared/Managers/CoreData/CoreDataManager+Chapter.swift
- Shared/Managers/CoreData/CoreDataManager+Manga.swift
- Shared/Managers/Manga/MangaManager.swift
- Shared/Models/Manga.swift
- Shared/Sources/Source.swift
- iOS/UI/Library/LibraryViewModel.swift
- iOS/UI/Manga/ChapterListHeaderConfiguration.swift
- iOS/UI/Manga/MangaViewController.swift
- iOS/UI/Manga/MangaViewModel.swift
I'm getting the available languages list using the source settings. IMO iterating the full chapter list is a bit overkill, but let me know if you want to change it.
Closes #144
> Filter chapters by language

- Shared/Extensions/Reachability.swift
- iOS/UI/Manga/MangaViewController.swift
> fix: empty chapter list when offline refreshing

- iOS/UI/Manga/MangaCoverViewController.swift
- iOS/UI/Manga/MangaViewController.swift
> CoverView: fix cloudflare images not loading

- Shared/Data/Downloads/DownloadTask.swift
Right now all files are saved with a .png extension regardless of their mimetype.
This attempts to guess the proper extension based on mimetype in the http response.
[UTType](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype-swift.struct/init(mimetype:conformingto:)) requires iOS 14+
> Guess file extension on download

- Shared/Data/Downloads/DownloadManager.swift
- Shared/Data/Downloads/DownloadQueue.swift
- Shared/Data/Downloads/DownloadTask.swift
- Shared/Data/Downloads/Models/Download.swift
- Shared/Old Models/Chapter.swift
- iOS/Old UI/Library/DownloadQueueViewController.swift
- iOS/UI/Library/LibraryViewController.swift
> Add download queue persistence

- iOS/UI/Reader/ReaderViewController.swift
- Closes #535
- Added support for showing title if chapter number and volume number not exist
| Chapter | Before | After |
| :-: | :-: | :-: |
| ![chapter1](https://github.com/user-attachments/assets/529f9022-8ccb-45e6-bb9c-4246f3c6abdb) | ![chapter1-before](https://github.com/user-attachments/assets/e7f9b352-a3d9-4137-a75c-5fbe7faaf020) | ![chapter1-after](https://github.com/user-attachments/assets/8e334326-82fd-498d-b591-952faa5cb756) |
| ![chapter2](https://github.com/user-attachments/assets/21b66485-db13-4620-a3c4-fe85eecbcf6a) | ![chapter2-before](https://github.com/user-attachments/assets/414f8722-27de-4e7a-b0c6-d789a6237799) | ![chapter2-after](https://github.com/user-attachments/assets/227e06f7-6406-4800-9c58-e0f6d82ffb3e) |
| …
> feat(reader): show title in navbar

- iOS/Extensions/UIImage.swift
- iOS/UI/Manga/MangaCoverViewController.swift
- iOS/UI/Reader/Readers/Paged/ReaderPagedViewController.swift
- Closes #537
- Added support for saving images to the app album
| Cover| Page | Album |
| :-: | :-: | :-: |
| ![cover](https://github.com/user-attachments/assets/ff146ca3-4cbb-45b1-9a1b-4225e03f61b3) | ![page](https://github.com/user-attachments/assets/6ce711cf-1e2d-4aff-8d4e-183d4b81ad89) | ![album](https://github.com/user-attachments/assets/0f582414-7f43-40b2-bb25-b21ef07ea74b) |
> feat: save images to album

- iOS/SceneDelegate.swift
Closes #488 
When in incognito mode, the app preview is blurred when switching apps.
> Add blur on app switch when incognito

- .gitignore
- Shared/Localization/en.lproj/Localizable.strings
- iOS/UI/Reader/ReaderViewController.swift
- Closes #318
- Added support for opening chapter in web view
| :-: | :-: |
| <video src="https://github.com/user-attachments/assets/3e38a65b-f474-4631-a7bc-66938fd8e4f7"> | <video src="https://github.com/user-attachments/assets/1d021031-7d5b-4b1d-a66d-f6c7ebd057b4"> |
> feat(reader): open chapter in web view

- .gitignore
- Shared/Localization/en.lproj/Localizable.strings
- iOS/Extensions/UIImage.swift
- iOS/UI/Manga/MangaCoverViewController.swift
- iOS/UI/Reader/Readers/Paged/ReaderPagedViewController.swift
- #545
- Added support for opening settings if photo library access was denied
| :-: | :-: |
| <video src="https://github.com/user-attachments/assets/4998b187-881e-463c-8c52-5178f9f47cdc"> | <video src="https://github.com/user-attachments/assets/815d6678-8bde-421c-9836-4a3bbf14922a"> |
> feat: check photo library access

- Shared/Localization/en.lproj/Localizable.strings
- iOS/AppDelegate.swift
- iOS/Old UI/Base/Settings/SettingSelectViewController.swift
- iOS/Old UI/Reader/ReaderNavigationController.swift
- iOS/Old UI/Reader/ReaderSettingsViewController.swift
- iOS/Old UI/Settings/SettingsViewController.swift
- Closes #48
- Added support for locking reader orientation 
https://github.com/user-attachments/assets/b548dfd1-3d7a-4460-badb-e5b5b87afdde
> feat(reader): lock orientation

- Shared/Data/Backup/BackupManager.swift
- Shared/Data/Backup/Models/Backup.swift
- Shared/Sources/SourceManager.swift
- Closes #110
- Added support for backing up and restoring source lists
| :-: | :-: |
| ![before](https://github.com/user-attachments/assets/41b9f415-1932-4055-9c02-82c69ff1eaeb) | ![after](https://github.com/user-attachments/assets/f51413ca-6b1a-4989-be40-d96b266db5dd) |
https://github.com/user-attachments/assets/bbe74197-c168-4fd2-9114-1778f6b59e25
> feat(backup): backup and restore source lists

- iOS/Old UI/Base/Settings/SettingSelectViewController.swift
- iOS/UI/Reader/ReaderViewController.swift
> fix: weak self

- Shared/Localization/en.lproj/Localizable.strings
- iOS/UI/Reader/Page/ReaderPageView.swift
- iOS/UI/Reader/Readers/Paged/ReaderPagedViewController.swift
- iOS/UI/Reader/Readers/Webtoon/ReaderWebtoonPageNode.swift
- iOS/UI/Reader/Readers/Webtoon/ReaderWebtoonViewController.swift
Mistakenly pushed to wrong branch and then hard reset to wrong commit, sorry for the additional PR
Closes #423
> Implement Image Reload - Issue Aidoku#423

- Aidoku.xcodeproj/project.pbxproj
- Shared/Localization/en.lproj/Localizable.strings
- iOS/Extensions/UIKeyModifierFlags.swift
- iOS/Old UI/History/HistoryViewController.swift
- iOS/Old UI/Search/SearchViewController.swift
- iOS/SceneDelegate.swift
- iOS/UI/Common/Manga/MangaCollectionViewController.swift
- iOS/UI/Common/TabBarController.swift
- iOS/UI/Reader/ReaderViewController.swift
partial reimplementation of #58. adds support for changing tabs, moving cells in library, and turning pages in reader.
closes #446
> feat: add keyboard support

- Shared/Localization/en.lproj/Localizable.strings
- Shared/Localization/zh-Hans.lproj/Localizable.strings
- Shared/Localization/zh-Hant.lproj/Localizable.strings
- iOS/New/Views/Reader/ReaderSettingsView.swift
- iOS/New/Views/Settings/Settings.swift
- iOS/UI/Reader/Readers/Paged/ReaderPageViewController.swift
- iOS/UI/Reader/Readers/Paged/ReaderPagedViewController.swift
Closes #96
Partial fix for #445
> feat: implement wide image detection and page offset functions in double page layout
